name: Update BlackLight Bot
 
on:
  push:
    branches: [main]
 
jobs:
    deploy:
        runs-on: windows-2019
        steps:
          - name: Update BlackLight Bot and Redeploy
            uses: fifsky/ssh-action@master
            with:
                host: ${{secrets.SSH_HOST}}
                user: ${{secrets.SSH_USERNAME}}
                pass: ${{secrets.SSH_PASSWORD}}
                command: |
                    D:
                    cd D:/Scripts/Personal/BlackLight-Bot
                    git pull
                    cd BlackLight_Bot_Source
                    npm install
                    taskkill /IM node.exe /F
                    RunBot.bat