name: Update BlackLight Bot
 
on:
  push:
    branches: [main]
 
jobs:
    deploy:
        runs-on: windows-2019
        steps:
          - name: Update BlackLight Bot and Redeploy
            uses: appleboy/ssh-action@v0.1.2
            with:
                host: ${{secrets.SSH_HOST}}
                username: ${{secrets.SSH_USERNAME}}
                password: ${{secrets.SSH_PASSWORD}}
                script: |
                    D:
                    cd D:/Scripts/Personal/BlackLight-Bot
                    git pull
                    cd BlackLight_Bot_Source
                    npm install
                    taskkill /IM node.exe /F
                    RunBot.bat